# Generated by Django 4.2.5 on 2023-10-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pin',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
